import {WEATHER} from '@/registry/WEATHER/WEATHER'

interface IWeatherItem {
    value: string,
    label: string
}

interface I_WEATHER_STORE_ {
    TEMPERATURE: IWeatherItem,
    PRECIPITATION: IWeatherItem,
    WIND_STRENGTH: IWeatherItem,
    WIND_DIRECTION: IWeatherItem,
}

const _WEATHER_STORE_: I_WEATHER_STORE_ = {
    TEMPERATURE: WEATHER.TEMPERATURE.WARM,

    PRECIPITATION: WEATHER.PRECIPITATION.DRY,

    WIND_STRENGTH: WEATHER.WIND_STRENGTH.WEAK,

    WIND_DIRECTION: WEATHER.WIND_DIRECTION.SOUTH_WEST
}

export {_WEATHER_STORE_}