import {WEATHER} from '@/registry/WEATHER/WEATHER'

const _WEATHER_STORE_ = {
    TEMPERATURE: WEATHER.TEMPERATURE.WARM,

    WIND_STRENGTH: WEATHER.WIND_STRENGTH.WEAK,

    WIND_DIRECTION: WEATHER.WIND_DIRECTION.SOUTH_WEST
}

export {_WEATHER_STORE_}